import TelmomentenBeheer from "./TelmomentenBeheer";
import ZonesBeheer from "./ZonesBeheer";
import ClustersBeheer from "./ClustersBeheer";

function BeheerderDashboard({
  telmomenten,
  nieuwTelmomentNaam,
  setNieuwTelmomentNaam,
  nieuwTelmomentDatum,
  setNieuwTelmomentDatum,
  nieuwTelmomentTijdstip,
  setNieuwTelmomentTijdstip,
  voegTelmomentToe,
  verwijderTelmoment,
  clusters,
  actiefClusterId,
  openClusterId,
  nieuweClusterNaam,
  setNieuweClusterNaam,
  voegClusterToe,
  selecteerCluster,
  toggleClusterOpen,
  toggleClusterZone,
  verwijderCluster,
  wijzigClusterNaam,
  nieuweZoneNaam,
  setNieuweZoneNaam,
  nieuweCapaciteit,
  setNieuweCapaciteit,
  voegZoneToe,
  zones,
  actieveZoneId,
  actiefTelmoment,
  krijgNummerplaten,
  telmomentLabel,
  bepaalKleur,
  selecteerZone,
  toggleZoneOpen,
  isBeheerder,
  isInvuller,
  tekenmodus,
  setTekenmodus,
  setBewerkmodusZoneId,
  setActieveZoneId,
  verwijderLaatstePunt,
  toggleBewerkmodus,
  wisPolygoon,
  verwijderZone,
  wijzigZoneNaam,
  wijzigZoneRegime,
  wijzigZoneMaxParkeerduur,
  wijzigZoneCapaciteit,
  parkeerRegimes,
  regimesMetMaxDuur,
  bewerkmodusZoneId,
  wijzigInvoer,
  voegNummerplaatToe,
  verwijderNummerplaat,
}) {
  return (
    <>
      <TelmomentenBeheer
        telmomenten={telmomenten}
        nieuwTelmomentNaam={nieuwTelmomentNaam}
        setNieuwTelmomentNaam={setNieuwTelmomentNaam}
        nieuwTelmomentDatum={nieuwTelmomentDatum}
        setNieuwTelmomentDatum={setNieuwTelmomentDatum}
        nieuwTelmomentTijdstip={nieuwTelmomentTijdstip}
        setNieuwTelmomentTijdstip={setNieuwTelmomentTijdstip}
        voegTelmomentToe={voegTelmomentToe}
        verwijderTelmoment={verwijderTelmoment}
      />

      <ZonesBeheer
        nieuweZoneNaam={nieuweZoneNaam}
        setNieuweZoneNaam={setNieuweZoneNaam}
        nieuweCapaciteit={nieuweCapaciteit}
        setNieuweCapaciteit={setNieuweCapaciteit}
        voegZoneToe={voegZoneToe}
        zones={zones}
        actieveZoneId={actieveZoneId}
        actiefTelmoment={actiefTelmoment}
        krijgNummerplaten={krijgNummerplaten}
        telmomentLabel={telmomentLabel}
        bepaalKleur={bepaalKleur}
        selecteerZone={selecteerZone}
        toggleZoneOpen={toggleZoneOpen}
        isBeheerder={isBeheerder}
        isInvuller={isInvuller}
        tekenmodus={tekenmodus}
        setTekenmodus={setTekenmodus}
        setBewerkmodusZoneId={setBewerkmodusZoneId}
        setActieveZoneId={setActieveZoneId}
        verwijderLaatstePunt={verwijderLaatstePunt}
        toggleBewerkmodus={toggleBewerkmodus}
        wisPolygoon={wisPolygoon}
        verwijderZone={verwijderZone}
        wijzigZoneNaam={wijzigZoneNaam}
        wijzigZoneRegime={wijzigZoneRegime}
        wijzigZoneMaxParkeerduur={wijzigZoneMaxParkeerduur}
        wijzigZoneCapaciteit={wijzigZoneCapaciteit}
        parkeerRegimes={parkeerRegimes}
        regimesMetMaxDuur={regimesMetMaxDuur}
        bewerkmodusZoneId={bewerkmodusZoneId}
        wijzigInvoer={wijzigInvoer}
        voegNummerplaatToe={voegNummerplaatToe}
        verwijderNummerplaat={verwijderNummerplaat}
      />

      <ClustersBeheer
        clusters={clusters}
        zones={zones}
        actiefClusterId={actiefClusterId}
        openClusterId={openClusterId}
        nieuweClusterNaam={nieuweClusterNaam}
        setNieuweClusterNaam={setNieuweClusterNaam}
        voegClusterToe={voegClusterToe}
        selecteerCluster={selecteerCluster}
        toggleClusterOpen={toggleClusterOpen}
        toggleClusterZone={toggleClusterZone}
        verwijderCluster={verwijderCluster}
        wijzigClusterNaam={wijzigClusterNaam}
      />
    </>
  );
}

export default BeheerderDashboard;
